INSERT INTO puzzles (id, domain, question, flag, difficulty, time_limit, hint1, hint2, hint3) VALUES
(1, 'cryptography', 'Decode this Caesar Cipher: KHOOR ZRUOG', 'HELLO WORLD', 1, 300, 'Think about a famous Roman cipher.', 'Every letter is shifted equally.', 'Shift each character back by 3.'),
(2, 'cryptography', 'Decode the binary message: 01001000 01001001', 'HI', 1, 240, 'Binary uses only two digits.', 'Convert each 8-bit group into ASCII.', '01001000 = H and 01001001 = I.'),
(3, 'cryptography', 'A secret message is encrypted using reverse text: DLROW OLLEH', 'HELLO WORLD', 2, 300, 'Sometimes the simplest encryption is reversal.', 'Try reading the message backwards.', 'Reverse the entire string to get the answer.'),
(4, 'web', 'Inspect the webpage source code to find the hidden flag inside an HTML comment.', 'FLAG{VIEW_SOURCE}', 1, 300, 'Browsers can reveal more than what is visible.', 'Right click and inspect the page source.', 'Look for <!-- hidden comments --> in the HTML.'),
(5, 'web', 'The flag is hidden using white text on a white background.', 'FLAG{HIDDEN_TEXT}', 2, 300, 'Not everything invisible is removed.', 'Try selecting all the text on the page.', 'Use Ctrl + A to reveal hidden white-colored text.'),
(6, 'web', 'A JavaScript cookie contains the hidden flag.', 'FLAG{COOKIE_MONSTER}', 2, 300, 'Websites store small pieces of data locally.', 'Open Developer Tools and inspect cookies.', 'Check document.cookie in the browser console.'),
(7, 'forensics', 'An image file contains hidden metadata with the flag.', 'FLAG{EXIF_FOUND}', 2, 300, 'Images store extra information beyond pixels.', 'Check the metadata of the image file.', 'Use exiftool or inspect EXIF metadata.'),
(8, 'forensics', 'Analyze the server logs and identify the suspicious IP address.', 'FLAG{192.168.1.66}', 3, 420, 'Look for unusual repeated activity.', 'Check failed login attempts carefully.', 'The suspicious IP appears multiple times in failed requests.'),
(9, 'forensics', 'A hidden message is embedded inside an audio spectrogram.', 'FLAG{SPECTROGRAM_SECRET}', 3, 420, 'Audio can hide visual information.', 'Convert the audio into a spectrogram image.', 'Use spectrogram analysis tools to reveal hidden text.'),
(10, 'database', 'Login bypass using SQL injection.', 'FLAG{SQLI_LOGIN}', 2, 300, 'Inputs can sometimes break queries.', 'Think about login conditions.', 'Use '' OR 1=1 -- to bypass authentication.'),
(11, 'database', 'Find the hidden admin record in the database.', 'FLAG{HIDDEN_ROW}', 2, 300, 'Not all data is shown by default.', 'Use filtering in SQL.', 'Try WHERE role = ''admin''.'),
(12, 'database', 'Perform a blind SQL injection to extract data.', 'FLAG{BLIND_SQLI}', 3, 300, 'You won’t see direct output.', 'Think in terms of true or false.', 'Use AND conditions like 1=1 and 1=2.');